spring:
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.schema.internal.script.MultiLineSqlScriptExtractor
  datasource:
    url: jdbc:h2:mem:carClub
  liquibase:
    contexts: dev
  web:
    resources:
      static-locations: classpath:/static/,file:uploads/
app:
  storage:
    location: uploads
